-- Reminders that assume something about the reader are removed and replaced.
--
-- The old set guessed at circumstances: that you are a parent, that you have a
-- job, that you are ill, that you are grieving. When the guess is wrong the
-- message stops feeling personal and starts feeling awkward, which is the
-- opposite of the intent. These speak to what everyone actually has in common:
-- worry, tiredness, waiting, regret, and needing to be told you are not alone.

delete from public.daily_reminders;

insert into public.daily_reminders (reminder, theme) values
('There is something you have been turning over for a while now, and it has not resolved itself. You are allowed to bring it to God exactly as it is, unfinished and unclear. You do not need better words for it. Being honest about what is heavy is not a lack of faith. It is the beginning of putting it somewhere other than your own shoulders.', 'Peace during stressful moments'),
('You are probably harder on yourself than you would ever be with someone else in your position. Notice that today. God is not adding his voice to that criticism. He sees the whole of you, including the parts you would rather nobody looked at, and he is not put off by any of it.', 'God''s love'),
('Not every day needs to be productive to be worth something. If today was slow, or you did less than you meant to, that does not make it wasted. You are not measured by output. Rest is part of how you were made to work, and taking it is obedience rather than laziness. Let today be enough as it was.', 'Rest when feeling tired'),
('Fear grows in the dark and shrinks when you say it out loud. Whatever is worrying you, name it plainly, either to God or to one person you trust. Most fears lose some of their size the moment they are spoken. The situation may not change tonight, but you do not have to carry it silently while it does.', 'Courage when facing fear'),
('Waiting is uncomfortable because nothing appears to be happening. It rarely feels like faith while you are in it. But time spent trusting God without proof is exactly what trust means, and it counts even when it feels like nothing at all. You have not been forgotten, and you are not behind.', 'Hope while waiting'),
('Something you did or said is still bothering you. Apologise if you can, put it right if it is possible, and then let it go. Turning it over again tonight will not improve it. God has already dealt with it, and continuing to punish yourself for something forgiven does not honour him. Let today be the end of it.', 'Forgiveness and grace'),
('Strength is not a feeling. Most of the time it looks like doing the ordinary next thing while still tired. You do not need to feel capable in order to be capable. God gives what the day requires, usually just enough and rarely in advance. Look at what is in front of you rather than the whole week at once.', 'Strength during difficult times'),
('Decisions are hard when you cannot see how they end. You are not failing because the way ahead is unclear. Ask God, get advice from someone who knows you well, then choose with what you have. He can work with a decision made honestly, even one that turns out differently from how you hoped it might.', 'Wisdom and guidance'),
('Notice one thing today that went right. Not a big thing. A conversation that was easier than expected, a moment of quiet, food you did not have to worry about. Naming it does not cancel out what is hard. It just stops the hard thing being the only thing you can see, and that shift matters more than it sounds.', 'Gratitude'),
('Progress is rarely a straight line. You have a good stretch and then a setback, and it feels like starting over. It is not. Something that dips is still moving. Measure across months rather than days, and be as patient with yourself as you would be with anyone else making the same slow progress.', 'Patience'),
('Someone is going to have an easier day because of something small you do. A message sent, a bit of patience held onto, a job done without being asked. None of it will be noticed and it still counts. God sees the things nobody thanks you for, and those are usually what faithfulness actually looks like.', 'Purpose and faith'),
('If you have been holding it together in front of everyone, you are allowed to stop for a moment. Being honest about struggling is not weakness and it will not disappoint God. He already knows. Letting one person see the real version of how you are doing is usually where things start getting lighter.', 'Healing and comfort'),
('You have kept going at something for a long time with very little to show for it. That is exhausting and nobody has said thank you. Rest properly, then decide again tomorrow. Not because stopping would be wrong, but because it may be worth more than it currently looks from where you are standing.', 'Perseverance after disappointment'),
('You do not need the whole plan before you take the next step. Most people only ever get enough light for the bit of road immediately ahead. If that is where you are, you are not doing it wrong. Take the next honest step and trust God with the part you genuinely cannot work out yet.', 'Trusting God''s direction'),
('There is a difference between being busy and being weighed down. Busy passes when the week ends. Weighed down follows you into the evening. If that is you, work out what you are actually carrying, because it is rarely only the schedule. Bring the real thing to God and let someone take a piece of it.', 'Rest when feeling tired'),
('God is not distant today and he is not disappointed in you. Those two ideas cause more damage than almost anything else people believe about him. He is close, he is patient, and he is glad you are here. You do not have to earn that, or feel it strongly, for it to be true.', 'God''s love'),
('Something did not go the way you hoped and you are still adjusting to it. Disappointment deserves a bit of time rather than being argued away. Sit with it honestly. God is not asking you to pretend you are fine. He is asking you to trust him with the version of the future you did not choose.', 'Perseverance after disappointment'),
('Peace does not mean the situation resolved. It means you are not facing it alone, which is a different thing and often a better one. You may still be worried tonight and still be held. Try to stop measuring your faith by how calm you feel, because that was never the right measure of it.', 'Peace during stressful moments'),
('Be careful what you say about people today, especially the ones who are difficult. You do not have to feel warm towards someone to speak about them fairly. Start with not repeating the story, and notice how much easier the next conversation with them becomes. Grace usually begins somewhere that small.', 'Forgiveness and grace'),
('If you are tired in a way that sleep does not fix, that is worth paying attention to. It usually means something needs to change rather than that you need to try harder. Ask God for honesty about what it is, then tell someone, because that kind of tiredness rarely lifts while you carry it alone.', 'Rest when feeling tired'),
('You are not as far behind as you think. Comparison makes everyone else look further along, because you only see the finished parts of their lives and all of your own working out. God is not running you against anyone. Look at where you were a year ago rather than at where somebody else is now.', 'Hope while waiting'),
('Courage is usually small and unglamorous. Sending the message. Asking the question. Turning up somewhere you would rather avoid. Nobody applauds any of it and it still costs something. God is with you in the small brave things just as much as in the large ones, and today probably only asks for one.', 'Courage when facing fear'),
('Whatever is unresolved tonight will still be unresolved in the morning, and you will be better equipped to face it having slept. Worrying is not the same as preparing, though it convincingly feels like it at two in the morning. Put it down for now. God does not need you awake to keep working on it.', 'Peace during stressful moments'),
('You have more to be thankful for than you can hold in mind at once, and most of it is so ordinary that you stopped noticing years ago. Water that runs. A door that locks. Somebody who would answer if you called them. None of that is guaranteed to anyone, and today it was given to you again.', 'Gratitude');
